app:
  env: lite
  name: food-ordering
  version: 1.0.0
  port: 3200
  host: localhost

database:
  driver: sqlite3
  host: localhost
  port: 0
  username:
  password:
  database: food_ordering

logger:
  level: debug
  format: json
  output: stdout

